#TODO - start docker container and run maven lifecycle in it, then start app

services:
  web:
    build: .  # Builds the Spring Boot app from the Dockerfile in the current directory
    ports:
      - "8080:8080"  # Exposes port 8080 (for the Spring Boot app) to the host machine
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ContainerControl  # Connection URL to MySQL
      - SPRING_DATASOURCE_USERNAME=pedro.monteiro  # MySQL username
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}  # MySQL password (make sure to set this)
    depends_on:
      mysql:  # Ensures that MySQL starts before the web service starts
        condition: service_healthy
    networks:
      - app-network  # Attaches the web service to the app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 120s

  mysql: #container do sql
    image: mysql:latest  # Use official MySQL image version 8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}  # Root password for MySQL
      MYSQL_DATABASE: ContainerControl  # The database that should be created
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}  # User's password
    ports:
      - "3307:3306"  # Exposes MySQL default port
    volumes:
      - mysql-data:/var/lib/mysql  # Persists MySQL data between container restarts
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge

