#pipeline file for container control project
#trigger - dev
trigger:
  branches:
    include:
      - master # neste caso é master, depois de PR mudar ficheiro master para DEV
pool:
  vmImage: 'ubuntu-latest' #ubuntu image for the agent

stages:
  - stage: BuildAndTest
    displayName: "Build and test"
    jobs:
      - job: Build
        displayName: "Build job"
        steps:
          #check out code
          - task: Checkout@1
            displayName: "Checkout Code"

          #set up java 17
          - task: JavaToolInstaller@1
            displayName: "set up java 17"
            inputs:
                version: '17'
                jdkArchitectureOption: 'x64'
          #cache maven dependencies
          - task: Cache@2
            displayName: "Cache Maven Dependencies"
            inputs:
              key: 'maven | "$(Agent.OS)" | pom.xml'
              path: $(HOME)/.m2/repository
              cacheHitVar: 'MavenCacheRestored'

          #install dependencies and build
          - script: mvn --batch-mode --update-snapshots clean install -DskipTests
            displayName: "Build Project"


          #run unit and integration tests
          - script: mvn --batch-mode test
            displayName: "Run Unit and Integration Tests"

          # Publish Test Results
          - task: PublishTestResults@2
            displayName: "Publish Test Results"
            inputs:
              testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
              testRunTitle: "Maven Test Results"